// Static data for the website - will be replaced by database/CMS in later phases

export const instruments = [
  { id: 'guzheng', name: 'Guzheng', nameZh: '古筝', icon: '🎵', campuses: ['chatswood', 'burwood'] },
  { id: 'erhu', name: 'Erhu', nameZh: '二胡', icon: '🎻', campuses: ['chatswood', 'burwood'] },
  { id: 'pipa', name: 'Pipa', nameZh: '琵琶', icon: '🎸', campuses: ['chatswood', 'burwood'] },
  { id: 'dizi', name: 'Dizi', nameZh: '笛子', icon: '🎶', campuses: ['chatswood'] },
  { id: 'xiao', name: 'Xiao', nameZh: '箫', icon: '🎶', campuses: ['chatswood'] },
  { id: 'yangqin', name: 'Yangqin', nameZh: '扬琴', icon: '🎹', campuses: ['chatswood'] },
  { id: 'ruan', name: 'Ruan', nameZh: '阮', icon: '🎸', campuses: ['chatswood'] },
  { id: 'zhongruan', name: 'Zhongruan', nameZh: '中阮', icon: '🎸', campuses: ['chatswood'] },
  { id: 'liuqin', name: 'Liuqin', nameZh: '柳琴', icon: '🎸', campuses: ['chatswood'] },
  { id: 'hulusi', name: 'Hulusi', nameZh: '葫芦丝', icon: '🎶', campuses: ['chatswood'] },
  { id: 'sheng', name: 'Sheng', nameZh: '笙', icon: '🎶', campuses: ['chatswood'] },
  { id: 'suona', name: 'Suona', nameZh: '唢呐', icon: '🎺', campuses: ['chatswood'] },
  { id: 'daruan', name: 'Daruan', nameZh: '大阮', icon: '🎸', campuses: ['chatswood'] },
  { id: 'cello', name: 'Cello', nameZh: '大提琴', icon: '🎻', campuses: ['chatswood'] },
  { id: 'piano', name: 'Piano', nameZh: '钢琴', icon: '🎹', campuses: ['chatswood', 'burwood'] },
  { id: 'guqin', name: 'Guqin', nameZh: '古琴', icon: '🎵', campuses: ['chatswood'] },
  { id: 'vocal', name: 'Vocal / Singing', nameZh: '声乐', icon: '🎤', campuses: ['chatswood'] },
];

export const teachers = [
  {
    id: 'meya-dong',
    slug: 'meya-dong',
    name: 'Meya Dong',
    nameZh: '董芈雅',
    title: 'Director & Instructor',
    titleZh: '校长 & 教师',
    instruments: ['Dizi', 'Xiao', 'Hulusi'],
    instrumentsZh: ['笛子', '箫', '葫芦丝'],
    bio: 'Meya Dong is the founder and director of the Meya Conservatory of Chinese Music. With over 15 years of professional performance and teaching experience, she is passionate about sharing the beauty of Chinese wind instruments with students in Australia.',
    bioZh: '董芈雅是芈雅中乐学院的创始人和校长。拥有超过15年的专业演出和教学经验，她热衷于在澳大利亚与学生分享中国管乐器之美。',
    image: '/images/teachers/meya-dong.jpg',
    campuses: ['chatswood', 'burwood'],
  },
  {
    id: 'zina-fan',
    slug: 'zina-fan',
    name: 'Zina Fan',
    nameZh: '范子纳',
    title: 'Pipa & Ruan Instructor',
    titleZh: '琵琶 & 阮教师',
    instruments: ['Pipa', 'Ruan'],
    instrumentsZh: ['琵琶', '阮'],
    bio: 'Zina Fan is an accomplished pipa and ruan player with extensive performance experience in both traditional and contemporary Chinese music ensembles.',
    bioZh: '范子纳是一位资深琵琶和阮演奏家，在传统和现代中国音乐合奏方面拥有丰富的演出经验。',
    image: '/images/teachers/zina-fan.jpg',
    campuses: ['chatswood'],
  },
  {
    id: 'angela-feng',
    slug: 'angela-feng',
    name: 'Angela Feng',
    nameZh: '冯安琪',
    title: 'Yangqin, Piano & Singing Instructor',
    titleZh: '扬琴、钢琴 & 声乐教师',
    instruments: ['Yangqin', 'Piano', 'Singing'],
    instrumentsZh: ['扬琴', '钢琴', '声乐'],
    bio: 'Angela Feng is a versatile musician and educator specializing in yangqin, piano, and vocal instruction. Her diverse musical background enriches her teaching approach.',
    bioZh: '冯安琪是一位多才多艺的音乐家和教育者，专注于扬琴、钢琴和声乐教学。她多元的音乐背景丰富了她的教学方法。',
    image: '/images/teachers/angela-feng.jpg',
    campuses: ['chatswood', 'burwood'],
  },
  {
    id: 'ashley-sui',
    slug: 'ashley-sui',
    name: 'Ashley Sui',
    nameZh: '隋雅诗',
    title: 'Erhu Instructor',
    titleZh: '二胡教师',
    instruments: ['Erhu'],
    instrumentsZh: ['二胡'],
    bio: 'Ashley Sui is a dedicated erhu instructor with a deep understanding of both traditional and modern erhu repertoire. She brings warmth and patience to every lesson.',
    bioZh: '隋雅诗是一位专注的二胡教师，对传统和现代二胡曲目都有深入理解。她在每节课中都带来温暖和耐心。',
    image: '/images/teachers/ashley-sui.jpg',
    campuses: ['chatswood'],
  },
];

export const events = [
  {
    id: 'east-meets-west-2025',
    slug: 'east-meets-west-2025',
    title: 'East Meets West: A Symphony of Cultures',
    titleZh: '东西合璧：文化交响曲',
    date: '2025-11-08',
    time: '6:30 PM - 8:30 PM',
    venue: 'The Concourse Chatswood Concert Hall',
    venueZh: 'Chatswood音乐厅',
    description: 'Concert at the Concourse - a Traditional Chinese Music concert bringing together Eastern and Western musical traditions.',
    descriptionZh: '在Concourse音乐厅举办的传统中国音乐会，融合东西方音乐传统。',
    ticketPrice: 39,
    image: '/images/events/east-meets-west.jpg',
  },
  {
    id: 'unity-wsu-2024',
    slug: 'unity-wsu-2024',
    title: 'UNITY: Embracing Humanity, Community, and Opportunity with Western Sydney University',
    titleZh: 'UNITY：与西悉尼大学共同拥抱人性、社区与机遇',
    date: '2024-11-20',
    time: '7:00 PM - 9:00 PM',
    venue: 'Western Sydney University',
    venueZh: '西悉尼大学',
    description: 'A collaborative concert exploring themes of unity and cultural connection through music.',
    descriptionZh: '一场合作音乐会，通过音乐探索团结与文化连结的主题。',
    ticketPrice: 0,
    image: '/images/events/unity-wsu.jpg',
  },
  {
    id: 'symphonic-fusion-2024',
    slug: 'symphonic-fusion-2024',
    title: 'Symphonic Fusion - an Orient-West Musical Connection',
    titleZh: '交响融合 - 东西方音乐连接',
    date: '2024-10-10',
    time: '7:00 PM - 9:00 PM',
    venue: 'Sydney Town Hall',
    venueZh: '悉尼市政厅',
    description: 'A groundbreaking concert blending traditional Chinese instruments with Western symphonic elements.',
    descriptionZh: '一场开创性的音乐会，将传统中国乐器与西方交响乐元素融合。',
    ticketPrice: 35,
    image: '/images/events/symphonic-fusion.jpg',
  },
];

export const shopCategories = [
  {
    id: 'instruments',
    name: 'Musical Instruments',
    nameZh: '乐器销售',
    description: 'Traditional Chinese musical instruments for purchase, catering to both beginners and seasoned musicians.',
    descriptionZh: '传统中国乐器，适合初学者和资深音乐家。',
    image: '/images/shop/instruments.jpg',
  },
  {
    id: 'hanfu',
    name: 'Hanfu Rental',
    nameZh: '汉服租赁',
    description: 'Exquisite Hanfu attire for men, women, and children. Perfect for practice, cultural events, or performances.',
    descriptionZh: '精美汉服，男女老少皆宜。适合练习、文化活动或演出。',
    image: '/images/shop/hanfu.jpg',
  },
  {
    id: 'performance-wear',
    name: 'Performance Dresses',
    nameZh: '演出服装',
    description: 'Elegant performance dresses designed for stage presence and comfort during musical performances.',
    descriptionZh: '优雅的演出服装，专为舞台表现和演奏舒适度设计。',
    image: '/images/shop/performance-wear.jpg',
  },
  {
    id: 'practice-room',
    name: 'Practice Room Rental',
    nameZh: '琴房租赁',
    description: 'Well-equipped practice rooms available for hourly rental at our campuses.',
    descriptionZh: '设备齐全的琴房可按小时租用。',
    image: '/images/shop/practice-room.jpg',
  },
];

export const newsArticles = [
  {
    id: 'unity-wsu',
    slug: 'unity-wsu',
    title: 'UNITY: Embracing Humanity, Community, and Opportunity with Western Sydney University',
    titleZh: 'UNITY：与西悉尼大学共同拥抱人性、社区与机遇',
    date: '2024-11-20',
    excerpt: 'It all begins with an idea. Our collaboration with Western Sydney University brought together musicians and students for an unforgettable evening of cultural exchange.',
    excerptZh: '一切始于一个想法。我们与西悉尼大学的合作，将音乐家和学生聚集在一起，度过了一个难忘的文化交流之夜。',
    image: '/images/news/unity-wsu.jpg',
  },
  {
    id: 'symphonic-fusion',
    slug: 'symphonic-fusion',
    title: 'Symphonic Fusion - an Orient-West Musical Connection',
    titleZh: '交响融合 - 东西方音乐连接',
    date: '2024-10-10',
    excerpt: 'A groundbreaking concert that bridges Eastern and Western musical traditions, creating a unique sonic tapestry.',
    excerptZh: '一场开创性的音乐会，连接东西方音乐传统，创造独特的音乐织锦。',
    image: '/images/news/symphonic-fusion.jpg',
  },
];
